app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('about/', views.AboutTemplateView.as_view(), name='about'),
    path('contacts/', views.ContactsTemplateView.as_view(), name='contacts'),
    path('catalog/', views.CatalogListView.as_view(), name='catalog'),
    path('collections/', views.CollectionsListView.as_view(), name='collections'),
    path('collections/<slug:slug>/', views.CollectionDetailView.as_view(), name='collection_detail'),
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from config.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import os
from io import BytesIO

from django.db import models
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from django.core.files import File
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model

from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Transpose
from PIL import Image, ImageChops

from .utils import save_products_image, save_collections_image, only_int

User = get_user_model()


# ABSTRACT CLASSES

class CommonInfo(models.Model):
    name = models.CharField('Название', max_length=150)
    description = RichTextField('Описание')
    price = models.PositiveIntegerField('Цена')
    instruction = models.FileField('Инструкция по установке', blank=True, null=True)
    material = models.CharField('Материал', max_length=50, blank=True, null=True)
    color = models.CharField('Цвет', max_length=50, blank=True, null=True)
    patina = models.CharField('Патина', max_length=50, blank=True, null=True)
    made_in = models.CharField('Производство', max_length=50, blank=True, null=True)
    slug = models.SlugField('URL', max_length=100, unique=True)
    is_published = models.BooleanField('Опубликован', default=True)

    class Meta:
        abstract = True


class SpecificationsBase(models.Model):
    custom_specification = models.ForeignKey(
        'CustomSpecification', on_delete=models.CASCADE, verbose_name='Характеристика'
    )
    value = models.CharField('Значение', max_length=50)

    class Meta:
        abstract = True


# MODELS

class WebsiteInfo(models.Model):
    name = models.CharField('Название сайта', max_length=150)
    logo = models.ImageField('Логотип', default='images/logo.png')
    address = models.CharField('Адрес', max_length=200)
    phone_number = models.CharField('Телефон', max_length=15, validators=[only_int])
    email = models.EmailField('Email', max_length=32)
    vk = models.URLField('Ссылка на ВК', null=True, blank=True)
    telegram = models.URLField('Ссылка на Telegram', null=True, blank=True)
    youtube = models.URLField('Ссылка на YouTube', null=True, blank=True)

    def __str__(self):
        return 'Данные сайта'

    class Meta:
        verbose_name = 'данные сайта'
        verbose_name_plural = 'Данные сайта'


@receiver(post_save, sender=User)
def create_initial_website_info(sender, instance, created, **kwargs):
    if created:
        if instance.id == 1:
            WebsiteInfo.objects.create(
                name='Lovely Baby',
                address='г. Махачкала, пр. Шамиля 31г',
                phone_number='88002000600',
                email='support@lovelybaby.ru',
            )


class Category(models.Model):
    name = models.CharField('Название', max_length=100)
    image = models.FileField('Картинка (svg)', validators=[FileExtensionValidator(['svg'])], blank=True, null=True)
    slug = models.SlugField('URL', max_length=100, unique=True)
    is_published = models.BooleanField('Опубликован', default=True)

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'
        ordering = ['custom_order']


class Collection(CommonInfo):
    image = models.ImageField('Картинка', upload_to=save_collections_image)
    image_2 = models.ImageField('Картинка для главной', upload_to=save_collections_image)
    bed_size = models.CharField(
        'Кровать (ДxШxВ)', max_length=50, blank=True, null=True, help_text='Пример формата: 60x140x34 см.'
    )
    drawer_size = models.CharField(
        'Комод (ДxШxВ)', max_length=50, blank=True, null=True, help_text='Пример формата: 60x140x34 см.'
    )
    wardrobe_size = models.CharField(
        'Шкаф (ДxШxВ)', max_length=50, blank=True, null=True, help_text='Пример формата: 60x140x34 см.'
    )

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def get_absolute_url(self):
        return reverse('collection_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        template = Image.open(f'{os.path.dirname(__file__)}/collection_templates/template.png').convert('RGBA')
        mask = Image.open(f'{os.path.dirname(__file__)}/collection_templates/mask.png').convert('RGBA')

        uploaded_image = Image.open(self.image).convert('RGBA')

        width, height = mask.size
        uploaded_image = uploaded_image.resize((width, height))

        insert_image = ImageChops.multiply(mask, uploaded_image)
        insert_image = insert_image.resize((width, height))

        template.paste(insert_image, (48, 110), insert_image)

        image_io = BytesIO()
        template.save(image_io, 'PNG')

        split_image_name = self.image.name.rsplit('.')

        image_name = split_image_name[0]
        image_extension = split_image_name[-1]

        new_image = File(image_io, name=f'{image_name}_main_screen.{image_extension}')
        self.image_2 = new_image

        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'комплект'
        verbose_name_plural = 'Комплекты'
        ordering = ['custom_order']


class Product(CommonInfo):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE, verbose_name='Комплект')
    size = models.CharField(
        'Размеры ДxШxВ', max_length=50, blank=True, null=True, help_text='Пример формата: 60x140x34 см.'
    )

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'
        ordering = ['-custom_order']


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    image = models.ImageField('Картинка', upload_to=save_products_image, null=False)
    thumbnail = ImageSpecField(
        source='image',
        processors=[
            Transpose(),
            ResizeToFill(64, 40),
        ],
        format='PNG',
        options={'quality': 60},
    )

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def __str__(self):
        return str(self.product.name)

    class Meta:
        verbose_name = 'картинка'
        verbose_name_plural = 'Картинки'
        ordering = ['custom_order']


class CustomSpecification(models.Model):
    name = models.CharField('Название', max_length=100)

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'кастомная характеристика'
        verbose_name_plural = 'Кастомные характеристики'
        ordering = ['custom_order']


class AdditionalSpecificationCollection(SpecificationsBase):
    parent = models.ForeignKey(
        Collection, on_delete=models.CASCADE, verbose_name='Комплект', related_name='additional_specifications_collection'
    )

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def __str__(self):
        return str(self.custom_specification.name)

    class Meta:
        verbose_name = 'дополнительные характеристики'
        verbose_name_plural = 'Дополнительные характеристики'
        ordering = ['custom_order']


class AdditionalSpecificationProduct(SpecificationsBase):
    parent = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='additional_specifications_product'
    )

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def __str__(self):
        return str(self.custom_specification.name)

    class Meta:
        verbose_name = 'дополнительные характеристики'
        verbose_name_plural = 'Дополнительные характеристики'
        ordering = ['custom_order']


class Slider(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    is_published = models.BooleanField('Опубликован', default=True)

    custom_order = models.PositiveIntegerField('Кастомный порядок', default=0, blank=False, null=False)

    def __str__(self):
        return str(self.product.name)

    class Meta:
        verbose_name = 'слайдер'
        verbose_name_plural = 'Слайдер'
        ordering = ['custom_order']

templates/about.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}О компании{% endblock title %}

{% block content %}
    <section class="about">
        <div class="cw">

            {% include 'includes/messages.html' %}

            <div class="breadcrumbs">
                <div class="breadcrumbs__container">
                    <ul class="breadcrumbs__list">
                        <li class="breadcrumbs__item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumbs__item active"><a href="#">О компании</a></li>
                    </ul>
                </div>
            </div>

            <div class="about__wrapper">
                <div class="about__header">
                    <h1 class="about__title">
                        О компании
                    </h1>
                </div>
                <div class="about__main-text">
                    <p>Lovely Baby – компания производитель функциональной детской мебели из натуральных материалов. Мы
                        обладаем современным и технологичным производством, но при этом вкладываем теплоту своих рук в
                        каждое изделие.</p>
                </div>
                <div class="about__advantages">
                    <p>Мы производим, долговечную и безопасную детскую мебель, которая прослужит долгие годы и будет
                        радовать Вас эстетическим
                        и функциональным совершенством.</p>
                    <p>В основе каждого предмета наших коллекций лежит высокое качество материалов, функциональный
                        дизайн, а так же забота о безопасности и здоровье Ваших детей.</p>
                    <p>С помощью наших коллекций мебели Вы сможете сформировать уютную детскую комнату только
                        качественной и безопасной мебелью.</p>
                    <p>При этом каждая коллекция мебели уникальна и обладает своими отличительными чертами которые
                        позволят Вам реализовать ваши идеи, окружить ребенка заботой, с привить ему вкус к
                        прекрасному.</p>
                </div>
            </div>
        </div>
    </section>

    {% include 'includes/commercial_proposal_form.html' %}

{% endblock content %}

templates/catalog.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}Каталог{% endblock title %}

{% block content %}
    <section class="products">
        <div class="cw">
            <div class="breadcrumbs">
                <div class="breadcrumbs__container">
                    <ul class="breadcrumbs__list">
                        <li class="breadcrumbs__item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumbs__item active"><a href="#">Каталог</a></li>
                    </ul>
                </div>
            </div>

            {% for category in category_list %}
                {% if category.product_set.count > 0 %}
                    <div class="products main">
                        <div class="cw">
                            <div class="products__wrapper">
                                <div class="products__header section-header">
                                    <h1 class="title">{{ category.name }}</h1>
                                    <div class="subtitle">{{ category.product_set.count }} позиции</div>
                                </div>
                                <div class="products__container">

                                    {% for product in category.product_set.all|slice:'5' %}
                                        <div class="products__item product">
                                            <div class="product__container">
                                                <div class="product__images-container">
                                                    {% for product_image in product.productimage_set.all|slice:'1' %}
                                                        <a href="{{ product.get_absolute_url }}" class="product__image">
                                                            <img src="{{ product_image.image.url }}" alt="Кроватка">
                                                        </a>
                                                    {% endfor %}
                                                    {% if product.productimage_set.count > 1 %}
                                                        <div class="product__other-images">
                                                            {% for product_image in product.productimage_set.all|slice:'1:5' %}
                                                                <div class="product__other-image">
                                                                    <img src="{{ product_image.image.url }}" alt="кровать">
                                                                </div>
                                                            {% endfor %}
                                                        </div>
                                                    {% endif %}
                                                </div>

                                                <div class="product__info-block">
                                                    <div class="product__info">
                                                        <a href="{{ product.get_absolute_url }}" class="product__name">
                                                            {{ product.name }}
                                                        </a>
                                                        <a href="{{ product.collection.get_absolute_url }}" class="product__category">
                                                            {{ product.collection.name }}
                                                        </a>
                                                        <div class="product__price">
                                                            {{ product.price }}₽
                                                        </div>
                                                    </div>
                                                    <div class="product__links">
                                                        <a href="{{ product.get_absolute_url }}" class="product__btn btn transparent">Смотреть</a>
                                                        <a href="" class="product__btn btn">Отправить заявку</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}

                                    <div class="products__item other-products">
                                        <div class="other-products__container">
                                            <img src="{% static 'images/product-5.png' %}" class="other-products__image"
                                                 alt="Кровать">
                                            <img src="{% static 'images/product-6.png' %}" class="other-products__image"
                                                 alt="Кровать">
                                            <img src="{% static 'images/product-7.png' %}" class="other-products__image"
                                                 alt="Кровать">
                                            <a href="{{ category.get_absolute_url }}" class="other-products__show-more btn">
                                                Смотреть всё
                                            </a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>


    <section class="seo">
        <div class="cw">
            <div class="seo__container">
                <div class="default-text">
                    <p>Мы постоянно совершенствуем технологические процессы, наращиваем темпы производства и расширяем
                        ассортимент изготавливаемой продукции, в том числе новых видов отделок и цветов.</p>
                    <p>Для производства современных мебельных фасадов фабрикой Lovely Baby регулярно привлекаются
                        дизайнеры.</p>
                    <p>Клиенты ценят нас за высокое качество продукции, быструю обработку заявок, конкурентоспособные
                        цены, программы скидок, бонусов и выгодные условия работы. Наши покупатели получают качественную
                        продукцию, профессиональное консультирование, кратчайшие сроки поставок, в том числе и сложных
                        позиций.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/category_detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}{{ category.name }}{% endblock title %}

{% block content %}
    <section class="products">
        <div class="cw">
            <div class="breadcrumbs">
                <div class="breadcrumbs__container">
                    <ul class="breadcrumbs__list">
                        <li class="breadcrumbs__item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumbs__item active"><a href="#">{{ category.name }}</a></li>
                    </ul>
                </div>
            </div>

            <div class="products main">
                <div class="cw">
                    <div class="products__wrapper">
                        <div class="products__header section-header">
                            <h1 class="title">{{ category.name }}</h1>
                            <div class="subtitle">{{ category.product_set.count }} позиции</div>
                        </div>
                        <div class="products__container">

                        {% for product in object_list %}
                            <div class="products__item product">
                                <div class="product__container">
                                    <div class="product__images-container">
                                        {% for product_image in product.productimage_set.all|slice:'1' %}
                                            <a href="{{ product.get_absolute_url }}" class="product__image">
                                                <img src="{{ product_image.image.url }}" alt="Кроватка">
                                            </a>
                                        {% endfor %}
                                        {% if product.productimage_set.count > 1 %}
                                            <div class="product__other-images">
                                                {% for product_image in product.productimage_set.all|slice:'1:5' %}
                                                    <div class="product__other-image">
                                                        <img src="{{ product_image.image.url }}" alt="кровать">
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>

                                    <div class="product__info-block">
                                        <div class="product__info">
                                            <a href="{{ product.get_absolute_url }}" class="product__name">
                                                {{ product.name }}
                                            </a>
                                            <a href="{{ product.collection.get_absolute_url }}"
                                               class="product__category">
                                                {{ product.collection.name }}
                                            </a>
                                            <div class="product__price">
                                                {{ product.price }}₽
                                            </div>
                                        </div>
                                        <div class="product__links">
                                            <a href="{{ product.get_absolute_url }}"
                                               class="product__btn btn transparent">Смотреть</a>
                                            <a href="" class="product__btn btn">Отправить заявку</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        </div>

                        {% if is_paginated %}
                            <div class="pagination">
                                <div class="pagination__container">
                                    <ul class="pagination__list">
                                        {% if page_obj.has_previous %}
                                            <li class="pagination__item prev">
                                                <a href="?page={{ page_obj.previous_page_number }}"
                                                   data-title="Предыдущая"></a>
                                            </li>
                                        {% else %}
                                            <li class="pagination__item prev"
                                                style="pointer-events:none; opacity:0.6;">
                                                <a href="#" data-title="Предыдущая"></a>
                                            </li>
                                        {% endif %}

                                        {% for n in page_obj.paginator.page_range %}
                                            {% if page_obj.number == n %}
                                                <li class="pagination__item page active"><a
                                                        href="?page={{ n }}">{{ n }}</a>
                                                </li>
                                            {% elif n > page_obj.number|add:-5 and n < page_obj.number|add:5 %}
                                                <li class="pagination__item page"><a
                                                        href="?page={{ n }}">{{ n }}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next and page_obj.next_page_number <= page_obj.paginator.page_range|length %}
                                            <li class="pagination__item next">
                                                <a href="?page={{ page_obj.next_page_number }}"
                                                   data-title="Следующая"></a>
                                            </li>
                                        {% else %}
                                            <li class="pagination__item next"
                                                style="pointer-events:none; opacity:0.6;">
                                                <a href="#" data-title="Следующая"></a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="seo">
        <div class="cw">
            <div class="seo__container">
                <div class="default-text">
                    <p>Мы постоянно совершенствуем технологические процессы, наращиваем темпы производства и расширяем
                        ассортимент изготавливаемой продукции, в том числе новых видов отделок и цветов.</p>
                    <p>Для производства современных мебельных фасадов фабрикой Lovely Baby регулярно привлекаются
                        дизайнеры.</p>
                    <p>Клиенты ценят нас за высокое качество продукции, быструю обработку заявок, конкурентоспособные
                        цены, программы скидок, бонусов и выгодные условия работы. Наши покупатели получают качественную
                        продукцию, профессиональное консультирование, кратчайшие сроки поставок, в том числе и сложных
                        позиций.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}